#!/bin/sh

# Reload Environment
source /etc/env

# Set default value for app directory if its not provided
: ${GUNICORN_APPDIR:=/app}

# Set default value for app if it is not provided
: ${GUNICORN_APP:=main:app}

# Set total number of workers - as num cpus + 1
: ${GUNICORN_WORKERS:=$(( `nproc` + 1))} 

# Change to application directory
cd ${GUNICORN_APPDIR}
exec /usr/local/bin/gunicorn --workers ${GUNICORN_WORKERS} --worker-class="egg:meinheld#gunicorn_worker" --bind unix:/run/gunicorn.sock ${GUNICORN_APP}
